"""
Django settings for calmconnect_backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import logging
from django.core.management.utils import get_random_secret_key
from decouple import Csv, AutoConfig

# Load environment variables from .env file
env_config = AutoConfig(search_path=os.path.dirname(os.path.dirname(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY: Load secrets from environment variables ---
OPENAI_API_KEY = env_config("OPENAI_API_KEY", default="")
print(f"OpenAI API Key loaded: {'Yes' if OPENAI_API_KEY else 'No'}")

# CRITICAL: Generate a random secret key if not provided
SECRET_KEY = env_config("DJANGO_SECRET_KEY", default="")
if not SECRET_KEY:
    if env_config('DJANGO_DEBUG', default='True', cast=bool):
        # Development fallback - generate random key
        SECRET_KEY = get_random_secret_key()
        print("WARNING: Using auto-generated SECRET_KEY for development. Set DJANGO_SECRET_KEY in production!")
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable must be set in production!")

# Email settings - use environment variables
EMAIL_HOST = env_config('EMAIL_HOST', default='sandbox.smtp.mailtrap.io')
EMAIL_HOST_USER = env_config('EMAIL_HOST_USER', default='d2ded003c8e726')
EMAIL_HOST_PASSWORD = env_config('EMAIL_HOST_PASSWORD', default='7a1e018014057e')
EMAIL_PORT = env_config('EMAIL_PORT', default=2525, cast=int)
EMAIL_USE_TLS = env_config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = env_config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = env_config('DEFAULT_FROM_EMAIL', default='noreply@calmconnect.edu.ph')
SERVER_EMAIL = env_config('SERVER_EMAIL', default='server@calmconnect.edu.ph')

# --- SECURITY: Production settings ---
# Set to False in production
DEBUG = env_config('DJANGO_DEBUG', default=True, cast=bool)
# Get ALLOWED_HOSTS from environment or use default
allowed_hosts = env_config(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1,testserver,.up.railway.app,earnest-presence-production-5ca0.up.railway.app',
    cast=Csv()
)

# Ensure Railway domain is always included (in case env var doesn't include it)
railway_domains = ['.up.railway.app', 'earnest-presence-production-5ca0.up.railway.app', 'calmn-connect.up.railway.app']
for domain in railway_domains:
    if domain not in allowed_hosts:
        allowed_hosts.append(domain)

ALLOWED_HOSTS = allowed_hosts
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")

# DRF configuration to ensure browser session auth works for API endpoints
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CSRF trusted origins - include Railway domains
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'https://calmn-connect.up.railway.app',
    'https://earnest-presence-production-5ca0.up.railway.app',
]

# Add Railway domains dynamically if not already included
railway_csrf_domains = [
    'https://calmn-connect.up.railway.app',
    'https://earnest-presence-production-5ca0.up.railway.app',
]
for domain in railway_csrf_domains:
    if domain not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(domain)

# --- SECURITY: HTTPS and cookies ---
# Enable security settings in production
SECURE_SSL_REDIRECT = not DEBUG  # Force HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies in production
CSRF_COOKIE_SECURE = not DEBUG  # Secure CSRF cookies in production
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year HSTS in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# --- ENHANCED SECURITY SETTINGS ---
# Session Security
SESSION_COOKIE_AGE = env_config('SESSION_COOKIE_AGE', default=3600, cast=int)  # 1 hour default
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_COOKIE_SAMESITE = 'Strict'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire sessions on browser close
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request

# CSRF Security
# In development, allow JS to read the CSRF cookie so AJAX can send X-CSRFToken
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_USE_SESSIONS = False

# Additional Security Headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# --- SECURITY: Add django-ratelimit for API protection ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mentalhealth',
    'rest_framework',
    'channels',
    # Note: django-ratelimit is used as a decorator,
    # not as a Django app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'mentalhealth.middleware.SecurityMiddleware',  # Custom security middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mentalhealth.middleware.LoginSecurityMiddleware',  # Login security
    'mentalhealth.middleware.AuditLoggingMiddleware',  # Security logging
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mentalhealth.middleware.ContentSecurityMiddleware',  # CSP headers
]

# CSRF protection is enabled for all environments
# Railway domains are added to CSRF_TRUSTED_ORIGINS above
print("CSRF protection enabled with Railway domains in trusted origins")

ROOT_URLCONF = 'calmconnect_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Project-level templates
            os.path.join(BASE_DIR, 'mentalhealth/templates'),  # Main app templates folder (prioritized)
            os.path.join(BASE_DIR, 'mentalhealth/templates/mentalhealth'),  # App subfolder templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'calmconnect_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Database configuration
DATABASE_URL = os.environ.get('DATABASE_URL') or env_config('DATABASE_URL', default='')
print(f"DATABASE_URL from os.environ: {os.environ.get('DATABASE_URL', 'Not found')}")
print(f"DATABASE_URL from env_config: {env_config('DATABASE_URL', default='Not found')}")
print(f"Final DATABASE_URL: {'Set' if DATABASE_URL else 'Not set'}")

def parse_database_url(url):
    """Parse DATABASE_URL into Django DATABASES format"""
    if not url:
        return None

    # Handle SQLite URLs
    if url.startswith('sqlite:///'):
        db_path = url[10:]  # Remove 'sqlite:///'
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }

    # Expected format: postgresql://user:password@host:port/dbname
    if url.startswith('postgresql://'):
        # Remove postgresql://
        url = url[13:]
        # Split user:password@host:port/dbname
        if '@' in url:
            user_pass, host_port_db = url.split('@', 1)
            if ':' in user_pass:
                user, password = user_pass.split(':', 1)
            else:
                user = user_pass
                password = ''

            if '/' in host_port_db:
                host_port, dbname = host_port_db.rsplit('/', 1)
            else:
                host_port = host_port_db
                dbname = ''

            if ':' in host_port:
                host, port = host_port.split(':', 1)
                port = int(port)
            else:
                host = host_port
                port = 5432  # Default PostgreSQL port

            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': dbname,
                'USER': user,
                'PASSWORD': password,
                'HOST': host,
                'PORT': port,
                'OPTIONS': {
                    'sslmode': 'require',
                },
            }
    return None

# Handle database configuration - allow build-time operations without DATABASE_URL
if DATABASE_URL:
    print("EXECUTING: DATABASE_URL is set, parsing database configuration")
    parsed_db = parse_database_url(DATABASE_URL)
    if parsed_db:
        DATABASES = {
            'default': parsed_db
        }
        print("Database configured successfully from DATABASE_URL")
    else:
        print("ERROR: Could not parse DATABASE_URL")
        raise ValueError("Invalid DATABASE_URL format")
else:
    # Check if we're in a build context where DB isn't needed
    import sys

    # Always allow collectstatic - it doesn't need database access
    is_collectstatic = 'collectstatic' in ' '.join(sys.argv)

    # Allow build-time commands that don't need database connectivity
    build_commands = ['makemigrations', 'migrate', 'shell', 'dbshell', 'showmigrations']

    # Check if this is a build-time command
    is_build_command = len(sys.argv) > 1 and (
        sys.argv[1] in build_commands or
        (len(sys.argv) > 2 and sys.argv[2] in build_commands)
    )

    # Also check for Railway build environment or CI
    is_build_env = (
        os.environ.get('RAILWAY_ENVIRONMENT') or
        os.environ.get('CI') or
        os.environ.get('BUILD_ENV') or
        os.environ.get('DOCKER_BUILD') or
        os.environ.get('RAILWAY_PROJECT_ID') or
        os.environ.get('RAILWAY_STATIC_URL') or  # Railway sets this during build
        os.environ.get('SOURCE_COMMIT')  # Railway sets this during build
    )

    if is_collectstatic or is_build_command or is_build_env:
        command_name = 'collectstatic' if is_collectstatic else (sys.argv[1] if len(sys.argv) > 1 else 'build_env')
        print(f"WARNING: DATABASE_URL not set, but allowing command: {command_name}")
        # Use a dummy database configuration for operations that don't need DB
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': ':memory:',
            }
        }
    else:
        print("ERROR: DATABASE_URL not set. Please set DATABASE_URL environment variable.")
        print(f"Current command: {' '.join(sys.argv) if sys.argv else 'unknown'}")
        print(f"Environment variables: {list(os.environ.keys())}")
        raise ValueError("DATABASE_URL environment variable must be set")

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Optional: Add login/logout redirect URLs
LOGIN_REDIRECT_URL = 'index'  # Changed from 'dashboard' to 'index'
LOGOUT_REDIRECT_URL = '/login/'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name', 'full_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Increased from 8 to 12
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mentalhealth/static/mentalhealth'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
LOGIN_URL = 'login'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
AUTH_USER_MODEL = 'mentalhealth.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels Configuration
ASGI_APPLICATION = 'calmconnect_backend.asgi.application'

# Channel Layers (for WebSocket support)
REDIS_URL = env_config('REDIS_URL', default='redis://localhost:6379')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

# Ensure ASGI is used for both HTTP and WebSocket
# Comment out WSGI_APPLICATION to force ASGI usage
# WSGI_APPLICATION = 'calmconnect_backend.wsgi.application'

# --- SECURITY LOGGING ---
# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'security': {
            'format': '[SECURITY] {asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'calmconnect.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'formatter': 'security',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mentalhealth.middleware': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# --- PRIVACY POLICY & CONSENT ---
# Ensure your privacy policy and user consent modal are updated to reflect:
# - Use of OpenAI for feedback
# - Data sent to OpenAI is anonymized (no PII)
# - Users must consent before DASS21 test
#
# See frontend/modal and privacy policy template for details.
