# Generated by Django 5.1.3 on 2025-06-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0002_convert_counselors'),
        ('mentalhealth', '0003_add_counselor_foreign_key'),
    ]

    operations = [
    ]
