# Generated by Django 5.1.3 on 2025-06-28 01:57

import django.db.models.deletion
import mentalhealth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0006_set_default_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(default=mentalhealth.models.get_default_counselor, on_delete=django.db.models.deletion.PROTECT, to='mentalhealth.counselor'),
        ),
    ]
