# Generated by Django 5.1.3 on 2025-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0007_alter_appointment_counselor'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_counselor ADD COLUMN IF NOT EXISTS "
            "email VARCHAR(254) NULL;",
            reverse_sql="ALTER TABLE mentalhealth_counselor DROP COLUMN "
            "email;",
        ),
    ]
