# Generated by Django 5.1.3 on 2025-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0007_alter_appointment_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
