# Generated by Django 5.1.3 on 2025-07-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0008_counselor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
