# Generated by Django 5.1.3 on 2025-07-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0008_counselor_email'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_appointment ADD COLUMN IF NOT EXISTS "
            "cancelled_at TIMESTAMP WITH TIME ZONE NULL;",
            reverse_sql="ALTER TABLE mentalhealth_appointment DROP COLUMN "
            "cancelled_at;",
        ),
    ]
