# Generated by Django 5.1.3 on 2025-07-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0009_appointment_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='counselor_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='mentalhealth.counselor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('counselor', 'Cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
