# Generated by Django 5.1.3 on 2025-07-08 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0010_customuser_counselor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='counselor_profile',
        ),
        migrations.AddField(
            model_name='counselor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
