# Generated by Django 5.1.3 on 2025-07-08 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0010_customuser_counselor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='counselor_profile',
        ),
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_counselor ADD COLUMN IF NOT EXISTS "
            "user_id INTEGER REFERENCES mentalhealth_customuser(id) "
            "ON DELETE CASCADE NULL;",
            reverse_sql="ALTER TABLE mentalhealth_counselor DROP COLUMN "
            "user_id;",
        ),
    ]
