# Generated by Django 5.1.3 on 2025-07-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0011_remove_customuser_counselor_profile_counselor_user'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_appointment ADD COLUMN IF NOT EXISTS "
            "notes TEXT NULL;",
            reverse_sql="ALTER TABLE mentalhealth_appointment DROP COLUMN notes;",
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('assessment', 'Assessment Report'), ('session', 'Session Report'), ('urgent', 'Urgent Report')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalhealth.counselor')),
            ],
        ),
    ]
