# Generated by Django 5.1.3 on 2025-07-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0012_appointment_notes_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='available_times',
        ),
        migrations.AddField(
            model_name='counselor',
            name='available_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='available_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
