# Generated by Django 5.1.3 on 2025-07-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0012_appointment_notes_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='available_times',
        ),
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_counselor ADD COLUMN IF NOT EXISTS "
            "available_end_time TIME NULL;",
            reverse_sql="ALTER TABLE mentalhealth_counselor DROP COLUMN "
            "available_end_time;",
        ),
        migrations.RunSQL(
            "ALTER TABLE mentalhealth_counselor ADD COLUMN IF NOT EXISTS "
            "available_start_time TIME NULL;",
            reverse_sql="ALTER TABLE mentalhealth_counselor DROP COLUMN "
            "available_start_time;",
        ),
    ]
