# Generated by Django 5.1.3 on 2025-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0013_remove_counselor_available_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='day_schedules',
            field=models.JSONField(default=dict, help_text='Individual schedules for each day'),
        ),
    ]
