# Generated by Django 5.1.3 on 2025-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0015_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('archived', 'Archived'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
