# Generated by Django 5.1.3 on 2025-07-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0016_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mentalhealth.appointment'),
        ),
    ]
