# Generated by Django 5.1.3 on 2025-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0019_alter_notification_options_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
