# Generated by Django 5.1.3 on 2025-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0021_appointment_session_type_livesession_sessionmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_call_url',
            field=models.URLField(blank=True, help_text='Video call URL for remote sessions', null=True),
        ),
    ]
