# Generated by Django 5.1.3 on 2025-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0023_enhance_notifications'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'dismissed'], name='mentalhealt_user_id_64ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='mentalhealt_user_id_2a0ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='mentalhealt_priorit_ffa2b6_idx'),
        ),
    ]
