# Generated by Django 5.1.3 on 2025-10-04 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0025_alter_customuser_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDASSResult',
            fields=[
                ('dassresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentalhealth.dassresult')),
                ('encrypted_answers', models.TextField(blank=True, help_text='Encrypted JSON containing all DASS-21 answers', null=True)),
                ('encrypted_depression_score', models.TextField(blank=True, help_text='Encrypted depression score', null=True)),
                ('encrypted_anxiety_score', models.TextField(blank=True, help_text='Encrypted anxiety score', null=True)),
                ('encrypted_stress_score', models.TextField(blank=True, help_text='Encrypted stress score', null=True)),
                ('data_hash', models.CharField(blank=True, help_text='SHA-256 hash of original data for integrity verification', max_length=64)),
                ('consent_given', models.BooleanField(default=False, help_text='Whether user consented to data collection and storage')),
                ('consent_timestamp', models.DateTimeField(blank=True, help_text='When consent was given', null=True)),
                ('encryption_version', models.CharField(default='v1', help_text='Version of encryption used', max_length=10)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this record has been accessed')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time this record was accessed', null=True)),
            ],
            options={
                'verbose_name': 'Secure DASS Result',
                'verbose_name_plural': 'Secure DASS Results',
            },
            bases=('mentalhealth.dassresult',),
        ),
        migrations.CreateModel(
            name='DASSDataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('standard', 'Standard Retention (7 years)'), ('extended', 'Extended Retention (indefinite)'), ('anonymized', 'Anonymized Only'), ('deleted', 'Marked for Deletion')], default='standard', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for retention policy choice')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Staff member who approved this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retention_policies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dass_retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DASS Data Retention Policy',
                'verbose_name_plural': 'DASS Data Retention Policies',
                'unique_together': {('user', 'policy_type')},
            },
        ),
    ]
