# Generated by Django 5.1.3 on 2025-11-16 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0026_securedassresult_dassdataretentionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='MoodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('prediction_type', models.CharField(choices=[('short_term', 'Short Term (1-7 days)'), ('medium_term', 'Medium Term (1-4 weeks)'), ('long_term', 'Long Term (1-3 months)')], max_length=20)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('predicted_depression', models.FloatField(help_text='Predicted depression score (0-42)')),
                ('predicted_anxiety', models.FloatField(help_text='Predicted anxiety score (0-42)')),
                ('predicted_stress', models.FloatField(help_text='Predicted stress score (0-42)')),
                ('depression_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('anxiety_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('stress_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('prediction_reasoning', models.TextField(help_text='AI reasoning for the prediction')),
                ('behavioral_insights', models.JSONField(default=dict, help_text='Key behavioral patterns identified')),
                ('risk_factors', models.JSONField(default=list, help_text='Identified risk factors')),
                ('protective_factors', models.JSONField(default=list, help_text='Identified protective factors')),
                ('recommended_actions', models.JSONField(default=list, help_text='Suggested actions based on prediction')),
                ('follow_up_date', models.DateField(help_text='Suggested date for follow-up assessment')),
                ('based_on_data_points', models.IntegerField(default=0, help_text='Number of data points used for prediction')),
                ('prediction_model', models.CharField(default='ai_feedback', help_text='Model/version used for prediction', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['user', 'prediction_date'], name='mentalhealt_user_id_0d01eb_idx'), models.Index(fields=['user', 'prediction_type'], name='mentalhealt_user_id_6891be_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('dass_test', 'DASS21 Test Completion'), ('exercise', 'Relaxation Exercise'), ('appointment_booked', 'Appointment Booked'), ('appointment_attended', 'Appointment Attended'), ('appointment_cancelled', 'Appointment Cancelled'), ('feedback_submitted', 'Feedback Submitted'), ('profile_updated', 'Profile Updated'), ('notification_read', 'Notification Read'), ('page_view', 'Page View'), ('session_start', 'Live Session Start'), ('session_end', 'Live Session End')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping related actions', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'behavior_type', 'timestamp'], name='mentalhealt_user_id_97d42c_idx'), models.Index(fields=['user', 'timestamp'], name='mentalhealt_user_id_523b9c_idx')],
            },
        ),
    ]
