# Generated by Django 5.1.3 on 2025-11-22 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0028_alter_counselor_unit_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('counselor', 'Counselor'), ('student', 'Student')], max_length=10)),
                ('reason', models.TextField(help_text='Reason for requesting follow-up')),
                ('requested_date', models.DateField(blank=True, help_text='Preferred date for follow-up', null=True)),
                ('requested_time', models.TimeField(blank=True, help_text='Preferred time for follow-up', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('approved_denied_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('face_to_face', 'Face-to-Face'), ('remote', 'Remote/Online')], default='face_to_face', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_requests', to='mentalhealth.report')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_requests_made', to=settings.AUTH_USER_MODEL)),
                ('resulting_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_request', to='mentalhealth.appointment')),
            ],
            options={
                'verbose_name': 'Follow-up Request',
                'verbose_name_plural': 'Follow-up Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
