# Generated by Django 5.1.3 on 2025-11-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0029_add_followup_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='dassresult',
            name='followup_appointment',
            field=models.ForeignKey(blank=True, help_text='The follow-up appointment this assessment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_assessments', to='mentalhealth.appointment'),
        ),
        migrations.AddField(
            model_name='dassresult',
            name='is_followup',
            field=models.BooleanField(default=False, help_text='Whether this is a follow-up assessment'),
        ),
    ]
