# Generated by Django 5.1.3 on 2025-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0030_add_followup_fields_to_dassresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('report', 'Report'), ('system', 'System'), ('reminder', 'Reminder'), ('feedback', 'Feedback'), ('followup', 'Follow-up'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('report', 'Report'), ('system', 'System'), ('reminder', 'Reminder'), ('feedback', 'Feedback'), ('followup', 'Follow-up'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
