# Generated by Django 5.1.3 on 2025-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0031_alter_notification_category_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthTipsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depression_severity', models.CharField(max_length=20)),
                ('anxiety_severity', models.CharField(max_length=20)),
                ('stress_severity', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=20)),
                ('college', models.CharField(blank=True, max_length=10)),
                ('year_level', models.CharField(blank=True, max_length=2)),
                ('tips_content', models.TextField()),
                ('tips_title', models.CharField(default='💡 Mental Health Tips', max_length=100)),
                ('source', models.CharField(default='openai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['depression_severity', 'anxiety_severity', 'stress_severity'], name='mentalhealt_depress_9606d1_idx'), models.Index(fields=['risk_level', 'college', 'year_level'], name='mentalhealt_risk_le_620a4d_idx'), models.Index(fields=['last_used', 'usage_count'], name='mentalhealt_last_us_d8366c_idx')],
                'unique_together': {('depression_severity', 'anxiety_severity', 'stress_severity', 'risk_level', 'college', 'year_level')},
            },
        ),
    ]
