# Generated by Django 5.1.3 on 2025-12-01 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0032_mentalhealthtipscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False, help_text='Enable dark mode theme')),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', help_text='Text size preference', max_length=12)),
                ('assignment_reminders', models.BooleanField(default=True, help_text='Enable assignment reminders')),
                ('grade_updates', models.BooleanField(default=True, help_text='Enable grade update notifications')),
                ('study_session_alerts', models.BooleanField(default=True, help_text='Enable study session alerts')),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('immediate', 'Immediate')], default='daily', help_text='How often to receive notifications', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Application language', max_length=10)),
                ('high_contrast', models.BooleanField(default=False, help_text='Enable high contrast mode')),
                ('screen_reader', models.BooleanField(default=False, help_text='Optimize for screen readers')),
                ('reduced_motion', models.BooleanField(default=False, help_text='Reduce animations and transitions')),
                ('analytics_tracking', models.BooleanField(default=True, help_text='Allow analytics data collection')),
                ('profile_visibility', models.BooleanField(default=True, help_text='Make profile visible to counselors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
