# Generated by Django 5.1.3 on 2025-12-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0033_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='assignment_reminders',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='grade_updates',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notification_frequency',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='study_session_alerts',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text='Notification preferences with frequency settings'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='analytics_tracking',
            field=models.BooleanField(default=True, help_text='Allow analytics tracking'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', help_text='Preferred font size', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Preferred application language', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('counselors_only', 'Counselors Only'), ('private', 'Private')], default='counselors_only', help_text='Profile visibility to other users', max_length=20),
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
    ]
