# Generated by Django 5.1.3 on 2025-12-01 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0034_remove_usersettings_assignment_reminders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', help_text='Text size preference', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Application language', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text='User notification preferences with frequency settings'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('counselors_only', 'Counselors Only'), ('private', 'Private')], default='counselors_only', help_text='Profile visibility settings', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
