# Generated by Django 5.1.3 on 2025-12-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0036_appointment_cancelled_at_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='unit',
            field=models.CharField(choices=[('CASS', 'College of Arts and Social Sciences'), ('CEN', 'College of Engineering'), ('CBA', 'College of Business Administration'), ('COF', 'College of Fisheries'), ('CAG', 'College of Agriculture'), ('CHSI', 'College of Home Science and Industry'), ('CED', 'College of Education'), ('COS', 'College of Sciences'), ('CVSM', 'College of Veterinary Science and Medicine')], max_length=100),
        ),
    ]
