# Generated by Django 5.1.3 on 2025-12-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0038_rename_counselor_unit_to_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='available_times',
            field=models.JSONField(default=list),
        ),
    ]
