# Generated by Django 5.1.3 on 2025-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0039_counselor_available_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
